id: I16547B35
ocr_import_info:
  timestamp: '2023-09-26T03:44:04.210704+00:00'
  batch_id: batch-a542
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 04:11:40.294797+00:00
last_modified: 2023-09-26 04:11:40.294805+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN560
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN560
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་རྒྱ་ཆེར་བཤད་པ།
  languages:
  - bo
  author: ལོ་ཆེན་སྐྱབས་མཆོག་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.9967210597276203
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN4029:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4029
      total_pages: 548
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4029.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9967210597276203
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
